dist: trusty
language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
    - CODECOV_TOKEN="bae73c57-83f4-479f-8129-9fa1783b92b8"
script: ./build.sh